blank_issues_enabled: false
contact_links:
  - name: You need configuration help
    url: https://github.com/qdm12/gluetun/discussions/new
    about: Please create a Github discussion.
  - name: Report a Gluetun bug or feature request
    url: https://github.com/qdm12/gluetun/issues/new
    about: Please create an issue on the gluetun repository.
  - name: Unraid template issue
    url: https://github.com/qdm12/gluetun/discussions/550
    about: Please read the relevant Github discussion.
