name: Closed issue
on:
  issues:
    types: [closed]

jobs:
  comment:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ github.token }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Closed issues are **NOT** monitored, so commenting here will NOT be
            seen by the maintainer. If you think this is *still unresolved* and
            have **more information** to bring, please create another issue.

            This is an automated comment setup because @qdm12 is the sole
            maintainer of this project which became too popular to monitor
            closed issues for additional comments.
